### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deadbits**
Hey! 👋

I've updated the tools section to add my recently released project `Vigil`. It's an open source Python app / REST API that can assess LLM prompts against a set of scanners to identify prompt injections and other suspicious inputs.

- https://github.com/deadbits/vigil-llm
- https://vigil.deadbits.ai/

### CODE REVIEW

**Comment by briland** [comment]
Hey there,

Thank you for your PR! 

Could you please provide the following information, so that it can be added to the [contributors.md](https://github.com/briland/LLM-security-and-privacy/blob/main/contributors.md) file:
- Contributor
- Website (optional)
- Institution (optional)
- GitHub profile (required)

Thank you,
Briland

**Comment by deadbits** [comment]
Sure thing, want me to open another PR with that info added in? Or just in this issue? I've added it below just in case

- Contributor: Adam Swanda
- Website (optional): https://www.deadbits.org
- Institution (optional): N/A
- GitHub profile (required): https://github.com/deadbits

**Comment by briland** [comment]
This is totally fine! I will update the table accordingly!

Thanks!

**Comment by deadbits** [comment]
Thank you!

**Pull request merged**
